version: 3

jobs:
  build:
    docker:
      - image: "circleci/node:10.16.3-browsers"
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - store_artifacts:
          path: coverage
          prefix: coverage
